"""Add debuffed field to BestStats

Revision ID: 366e83b95737
Revises: 95465d613972
Create Date: 2026-05-16 14:31:37.613635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366e83b95737'
down_revision = '95465d613972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('best_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debuffed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('best_stats', schema=None) as batch_op:
        batch_op.drop_column('debuffed')

    # ### end Alembic commands ###
