"""Replace GameSession with BestStats model

Revision ID: 581b22c3c894
Revises: fb119cb7702a
Create Date: 2026-05-09 17:52:47.010619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581b22c3c894'
down_revision = 'fb119cb7702a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highscore', sa.Integer(), nullable=True),
    sa.Column('longest_time', sa.Float(), nullable=True),
    sa.Column('jump_count', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_session')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('friend_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('friend_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    op.create_table('game_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=False),
    sa.Column('jump_count', sa.INTEGER(), nullable=True),
    sa.Column('currency_earned', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('best_stats')
    # ### end Alembic commands ###
