"""Update GameSession model to include jump count and currency earned

Revision ID: 58588b50c902
Revises: bde85e41f28a
Create Date: 2026-05-08 01:01:25.956447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58588b50c902'
down_revision = 'bde85e41f28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jump_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency_earned', sa.Integer(), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('currency_earned')
        batch_op.drop_column('jump_count')

    # ### end Alembic commands ###
