"""Add friendship table

Revision ID: 7a0e49f57acd
Revises: 8a0e46734aeb
Create Date: 2026-05-14 20:45:10.403752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0e49f57acd'
down_revision = '8a0e46734aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('friendID1', sa.Integer(), nullable=False),
    sa.Column('friendID2', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['friendID1'], ['account.id'], ),
    sa.ForeignKeyConstraint(['friendID2'], ['account.id'], ),
    sa.PrimaryKeyConstraint('friendID1', 'friendID2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    # ### end Alembic commands ###
