"""Change lengths of the email and username fields

Revision ID: 8a0e46734aeb
Revises: 04d7b45e726e
Create Date: 2026-05-14 20:09:43.217395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0e46734aeb'
down_revision = '04d7b45e726e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=18),
               existing_nullable=False)
        batch_op.create_foreign_key('profileAccountId', 'account', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('username',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
