"""Added is email verified field to Account model

Revision ID: 95465d613972
Revises: 7a0e49f57acd
Create Date: 2026-05-16 08:31:50.925101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95465d613972'
down_revision = '7a0e49f57acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('is_email_verified')

    # ### end Alembic commands ###
