"""Add Sabotage model

Revision ID: c4cbc5ef7aaa
Revises: 8a0e46734aeb
Create Date: 2026-05-15 21:56:23.485201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cbc5ef7aaa'
down_revision = '8a0e46734aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('friendID1', sa.Integer(), nullable=False),
    sa.Column('friendID2', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['friendID1'], ['account.id'], ),
    sa.ForeignKeyConstraint(['friendID2'], ['account.id'], ),
    sa.PrimaryKeyConstraint('friendID1', 'friendID2')
    )
    op.create_table('sabotage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('multiplier_debuff', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sabotage')
    op.drop_table('friendship')
    # ### end Alembic commands ###
