"""add has_bonus and bonus_timestamp fields

Revision ID: d85b7e6bd8ed
Revises: 366e83b95737
Create Date: 2026-05-17 21:31:31.292316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85b7e6bd8ed'
down_revision = '366e83b95737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('has_bonus', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('has_bonus')
        batch_op.drop_column('bonus_timestamp')

    # ### end Alembic commands ###
