"""Minimal starting Profile model for authentication purpose

Revision ID: efe1a2148a05
Revises: ebbfe235cf34
Create Date: 2026-05-07 22:50:19.110833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe1a2148a05'
down_revision = 'ebbfe235cf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('is_first_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_login', sa.BOOLEAN(), nullable=True))

    op.drop_table('profile')
    # ### end Alembic commands ###
