"""set friend_code nullable back to False

Revision ID: fb119cb7702a
Revises: 03c5206084d3
Create Date: 2026-05-08 21:19:02.214707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb119cb7702a'
down_revision = '03c5206084d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_account')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('friend_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('friend_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    op.create_table('_alembic_tmp_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('friend_code', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
